# Generated by Django 5.0.6 on 2024-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Formatador', models.CharField(choices=[('EXCEL', 'EXCEL'), ('PDF', 'PDF'), ('CSV', 'CSV')], max_length=100)),
            ],
        ),
    ]
