# Generated by Django 5.0.6 on 2024-06-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer_export', '0002_formatador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formatador',
        ),
    ]
